spring:
  #thymeleaf模板相关配置
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #开发禁用缓存
    cache: false
  #MySQL数据库连接参数
  datasource:
    url: jdbc:mysql://localhost:3306/testconn?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    #数据库连接超时时间
    hikari:
      connection-timeout: 60000
#tomcat服务器相关配置
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8